services:
- type: pserv
  name: elasticsearch
  env: docker
  plan: standard
  autoDeploy: false # so ES does not restart on a push to this repository.
  scaling:
    minInstances: 2         # Required
    maxInstances: 3         # Required
    targetMemoryPercent: 60 # Optional if targetCPUPercent is set (valid: 1-90)
    targetCPUPercent: 60    # Optional if targetMemory is set (valid: 1-90)
  envVars:
  - key: ES_JAVA_OPTS
    value: "-Xms512m -Xmx512m"
  - key: discovery.type
    value: single-node
  - key: cluster.name
    value: elastic736
